start_date: 2024-02-29
columns:
  Account: string
  Date: datetime
  Amount: float
  Memo/Notes: string
  Clr: string
  Split: string
  Scheduled: string
  Payee: string
  Category: string
  Tags: string
  Sync ID: string
  FITID: string
accounts:
  - Shared BofA Checking
  - Discover It
groupby_payees:
  - payee: ACME Inc
    category: Income
    notes: Paycheck
    tags: "#Income"
  - payee: Walmart
    category: Income
    notes: Paycheck
    tags: "#Income"
  - payee: The Mortgage Company
    category: Mortgage
    notes: Mortgage Transfer
    tags: "#House"